# Generated by Django 5.1.2 on 2024-11-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id_viaje', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Origen', models.CharField(max_length=50)),
                ('Destino', models.CharField(max_length=50)),
                ('Horario', models.CharField(max_length=50)),
                ('Distancia', models.CharField(max_length=50)),
                ('Paradas_Continuas', models.CharField(max_length=10)),
                ('Costo', models.CharField(max_length=10)),
            ],
        ),
    ]
